# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Alok Sethi"
email:
description: >- # this means to ignore newlines until "baseurl:"
  A peronsal blog where I place my projects, code snippets, etc. so that I can access them easilyt in the future.
#twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
enable_copy_code_button:  true

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alok Sethi"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : ""
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin fa-xl"
      url: "https://www.linkedin.com/in/sethialok/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Orcid"
      icon: "fa-brands fa-orcid fa-xl"
      url: "https://orcid.org/0000-0003-4748-8472"
    - label: "Scholar"
      icon: "fa-brands fa-google-scholar fa-xl"
      url: "https://scholar.google.com/citations?user=sjV_1cEAAAAJ"
      
#footer:
#  links:
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/"

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
    
sass:
  style: compressed


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # css
  - scope:
      path: "assets/css"
    values:
      css: "custom"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
